name: freebsd
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: vmactions/freebsd-vm@v1
        with:
          run: |
            pkg install -y libsodium
            make filly-test
            ./filly-test